### ISSUE TITLE
Антон вы не выходите на связь Антон Антон??

### ISSUE THREAD

**Issue by volhovm** [AVBelyy/Rysearch#1]
Добрый вечер. Добрый день. Здравствуйте.

[https://i.imgur.com/Hfv8B4S.png](https://i.imgur.com/Hfv8B4S.png)

Заходите, навещайте, не стесняйтесь!

Спасибо, всего доброго, до свидания, до посещения, с уважением,
Михаил Миша Механик

**Comment by AVBelyy** [comment]
Привет тебе Миша! Спасибо что навестил!

Я обязательно на днях зайду и даже расскажу кое-что интересное.

Увидимся!

- Антон AntoXa BarmatuXa
